version: '3.1'


services:

  api:
    build:
      dockerfile: "api/Dockerfile"
      context: .
    command: uwsgi --ini uwsgi.ini --py-autoreload=3 --honour-stdin
    stdin_open: true
    tty: true
    environment:
      - PYTHONIOENCODING=UTF-8
      - COLUMNS=80
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=api.settings
      - APPLICATION_MODE=${APPLICATION_MODE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nppo_middleware
    healthcheck:
      test: psql -U postgres nppo_middleware -c "SELECT 'DBD::Pg ping test'"
    labels:
      nl.publinova.db: "postgres"
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgres_database:
