from sources.extraction.django import DjangoPersonExtractProcessor, DjangoProjectExtractProcessor
from sources.extraction.hva import HvaPersonExtractProcessor
from sources.extraction.hku import HkuPersonExtractProcessor, HkuProjectExtractProcessor
from sources.extraction.buas import BuasPersonExtractProcessor, BuasProjectExtractProcessor
from sources.extraction.sharekit import SharekitPersonExtractProcessor
from sources.extraction.sia import SiaProjectExtractProcessor
from sources.extraction.hanze import HanzeProjectExtractProcessor, HanzePersonsExtractProcessor
