# Generated by Django 3.2.16 on 2023-06-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualperson',
            name='source',
            field=models.IntegerField(choices=[(1, 'Manual 1'), (2, 'Manual 2'), (3, 'Manual 3')], default=1),
        ),
        migrations.AddField(
            model_name='manualproject',
            name='source',
            field=models.IntegerField(choices=[(1, 'Manual 1'), (2, 'Manual 2'), (3, 'Manual 3')], default=1),
        ),
    ]
