# Generated by Django 3.2.5 on 2022-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_repository',
            field=models.BooleanField(default=False, help_text='Enable when source is a repository for multiple organizations'),
        ),
    ]
