# Generated by Django 3.2.16 on 2023-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_is_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='proxy_files',
            field=models.BooleanField(default=False, help_text='Enable when the source need to proxy files to circumvent authentication during file downloads'),
        ),
    ]
