PERSON_DEFAULTS = {
    "name": None,
    "external_id": None,
    "email": None,
    "orcid": None,
    "isni": None,
    "dai": None,
    "first_name": None,
    "last_name": None,
    "prefix": None,
    "initials": None,
    "title": None,
    "phone": None,
    "skills": [],
    "themes": [],
    "description": None,
    "parties": [],
    "photo_url": None,
    "is_employed": True,
    "job_title": None,
    "research_themes": [],
}


PROJECT_DEFAULTS = {
    "title": None,
    "external_id": None,
    "status": None,
    "started_at": None,
    "ended_at": None,
    "coordinates": [0, 0],
    "goal": None,
    "contacts": [],
    "persons": [],
    "owners": [],
    "description": None,
    "parties": [],
    "keywords": [],
    "products": [],
    "photo_url": None,
    "research_themes": [],
}
